version: '3'
services:
  autosync:
    container_name: autosync
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - ${SOURCEDIR}:/app/sourcedir
      - ${BACKUPDIR}:/app/backupdir
